sonar.projectKey=FlossWare_loom-ai
sonar.organization=flossware
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=docker:S8544
sonar.issue.ignore.multicriteria.e1.resourceKey=Dockerfile
