"""Tests for FreeModelRouter worker/arbiter consensus.

Generated by NVIDIA Nemotron 3 Ultra 550B (OpenRouter free tier).
Reviewed and corrected by Cohere Command-A.
Issue #805.
"""

from unittest.mock import AsyncMock, patch

import pytest

from loom_ai.backends.free_model_router import FreeModelRouter, _ModelEndpoint
from loom_ai.models import ChatMessage, ChatResponse


class TestFreeModelRouterConsensus:
    def setup_method(self):
        self.router = FreeModelRouter(consensus=True, n_workers=3)
        self.router._initialized = True
        self.router._endpoints = [
            _ModelEndpoint("openai", "gpt-4", "key1", "account1"),
            _ModelEndpoint("openai", "gpt-3.5", "key2", "account2"),
            _ModelEndpoint("anthropic", "claude-3", "key3", "account3"),
            _ModelEndpoint("anthropic", "claude-2", "key4", "account4"),
            _ModelEndpoint("google", "gemini-pro", "key5", "account5"),
            _ModelEndpoint("google", "gemini-flash", "key6", "account6"),
        ]

    def test_select_diverse_prefers_different_providers(self):
        selected = self.router._select_diverse_workers(3)
        providers = {ep.provider for ep in selected}
        assert len(providers) == 3
        assert len(selected) == 3

    def test_select_arbiter_excludes_providers(self):
        exclude = {"openai", "anthropic"}
        arbiter = self.router._select_arbiter(exclude)
        assert arbiter.provider == "google"
        assert arbiter.provider not in exclude

    @pytest.mark.asyncio
    async def test_consensus_chat_calls_workers_and_arbiter(self):
        messages = [ChatMessage("user", "test")]
        worker_response = ChatResponse(
            "worker response", "gpt-4", "openai", {"tokens": 10}
        )
        arbiter_response = ChatResponse(
            "arbiter response", "gemini-pro", "google", {"tokens": 15}
        )

        async def mock_call(ep, msgs, temp, max_tokens):
            if ep.provider == "google":
                return arbiter_response
            return worker_response

        with patch.object(
            self.router, "_call", side_effect=mock_call
        ) as mock_call_method:
            with patch.object(
                self.router,
                "_select_diverse_workers",
                return_value=[
                    _ModelEndpoint("openai", "gpt-4", "k1", "a1"),
                    _ModelEndpoint("anthropic", "claude-3", "k2", "a2"),
                    _ModelEndpoint("google", "gemini-pro", "k3", "a3"),
                ],
            ):
                with patch.object(
                    self.router,
                    "_select_arbiter",
                    return_value=_ModelEndpoint("google", "gemini-pro", "k3", "a3"),
                ):
                    result = await self.router.consensus_chat(
                        messages,
                        n_workers=3,
                        temperature=0.7,
                        max_tokens=100,
                    )

        assert result.content == "arbiter response"
        assert mock_call_method.call_count == 4

    @pytest.mark.asyncio
    async def test_consensus_chat_fallback_on_arbiter_failure(self):
        messages = [ChatMessage("user", "test")]
        worker_response = ChatResponse(
            "worker response", "gpt-4", "openai", {"tokens": 10}
        )

        async def mock_call(ep, msgs, temp, max_tokens):
            if ep.provider == "google":
                raise Exception("Arbiter failed")
            return worker_response

        with patch.object(
            self.router, "_call", side_effect=mock_call
        ) as mock_call_method:
            with patch.object(
                self.router,
                "_select_diverse_workers",
                return_value=[
                    _ModelEndpoint("openai", "gpt-4", "k1", "a1"),
                    _ModelEndpoint("anthropic", "claude-3", "k2", "a2"),
                ],
            ):
                with patch.object(
                    self.router,
                    "_select_arbiter",
                    return_value=_ModelEndpoint("google", "gemini-pro", "k3", "a3"),
                ):
                    result = await self.router.consensus_chat(
                        messages,
                        n_workers=2,
                        temperature=0.7,
                        max_tokens=100,
                    )

        assert result.content == "worker response"
        assert mock_call_method.call_count == 3

    @pytest.mark.asyncio
    async def test_chat_uses_consensus_when_enabled(self):
        messages = [ChatMessage("user", "test")]
        consensus_response = ChatResponse(
            "consensus", "gpt-4", "openai", {"tokens": 10}
        )

        with patch.object(
            self.router, "consensus_chat", new_callable=AsyncMock
        ) as mock_consensus:
            mock_consensus.return_value = consensus_response
            result = await self.router.chat(messages, temperature=0.7, max_tokens=100)

        mock_consensus.assert_called_once_with(
            messages, n_workers=3, temperature=0.7, max_tokens=100
        )
        assert result.content == "consensus"

    @pytest.mark.asyncio
    async def test_chat_skips_consensus_when_disabled(self):
        router_no_consensus = FreeModelRouter(consensus=False, n_workers=3)
        router_no_consensus._initialized = True
        router_no_consensus._endpoints = self.router._endpoints

        messages = [ChatMessage("user", "test")]
        fallback_response = ChatResponse("fallback", "gpt-4", "openai", {"tokens": 10})

        async def mock_call(ep, msgs, temp, max_tokens):
            return fallback_response

        with patch.object(
            router_no_consensus, "_call", side_effect=mock_call
        ) as mock_call_method:
            result = await router_no_consensus.chat(
                messages, temperature=0.7, max_tokens=100
            )

        assert mock_call_method.call_count >= 1
        assert result.content == "fallback"
