"""Adversarial verification with independent model panels.

Provides :class:`AdversarialVerifier`, which takes a candidate response
and asks a panel of *independent* models to critique and verify it.
Panel members are chosen to differ from the model that generated the
candidate, ensuring adversarial independence.

Verdicts
--------
- **CONFIRMED** -- a majority of panel members agree the response is
  correct and adequate.
- **REFUTED** -- a majority of panel members identify errors or
  inadequacies.
- **UNCERTAIN** -- the panel could not reach a clear majority.

Zero external dependencies -- uses only the standard library.
"""

from __future__ import annotations

import asyncio
import logging
import re
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Sequence

from loom_ai.models import ChatMessage

if TYPE_CHECKING:
    from loom_ai.protocols import LLMBackend

logger = logging.getLogger(__name__)

# ── Prompt template ────────────────────────────────────────────────────

_VERIFICATION_PROMPT = """\
You are an independent verification judge. Your job is to critically \
evaluate a candidate response that was generated by another AI model.

Original task: {task}

Candidate response to verify:
{candidate}

Analyze the candidate response and provide:
1. Whether the response correctly addresses the task
2. Any errors, omissions, or weaknesses you identify
3. Your verdict: CONFIRMED, REFUTED, or UNCERTAIN

Respond with EXACTLY these sections:
ANALYSIS: <your analysis>
ERRORS: <list any errors, or "none">
VERDICT: <CONFIRMED|REFUTED|UNCERTAIN>
"""

_VERDICT_PATTERN = re.compile(
    r"^VERDICT\s*:\s*(CONFIRMED|REFUTED|UNCERTAIN)\s*$",
    re.MULTILINE | re.IGNORECASE,
)


# ── Data types ─────────────────────────────────────────────────────────


@dataclass
class PanelMemberResult:
    """Verdict from a single panel member.

    Attributes
    ----------
    model:
        The model id that produced this verdict.
    verdict:
        One of ``"CONFIRMED"``, ``"REFUTED"``, ``"UNCERTAIN"``.
    raw_response:
        The full response text from the panel member.
    """

    model: str
    verdict: str
    raw_response: str


@dataclass
class VerificationResult:
    """Aggregated result from all panel members.

    Attributes
    ----------
    verdict:
        Final aggregated verdict (``"CONFIRMED"``, ``"REFUTED"``,
        ``"UNCERTAIN"``).
    panel_results:
        Individual verdicts from each panel member.
    confidence:
        Fraction of panel members that agree with the final verdict.
    candidate_model:
        The model that generated the original candidate.
    panel_models:
        Model ids used on the verification panel.
    """

    verdict: str
    panel_results: list[PanelMemberResult] = field(default_factory=list)
    confidence: float = 0.0
    candidate_model: str = ""
    panel_models: list[str] = field(default_factory=list)


# ── Panel selection ────────────────────────────────────────────────────


def select_panel(
    available_models: Sequence[str],
    candidate_model: str,
    *,
    panel_size: int = 3,
) -> list[str]:
    """Choose panel members that differ from *candidate_model*.

    Excludes the candidate model (and any model from the same family,
    determined by shared prefix before ``/`` or ``-``).  If not enough
    independent models are available, the panel may be smaller than
    *panel_size* but will never include the candidate itself.

    Parameters
    ----------
    available_models:
        Full list of model ids to choose from.
    candidate_model:
        The model that generated the candidate response.
    panel_size:
        Desired number of panel members (default ``3``).
    """
    if not available_models:
        return []

    # Derive a prefix to exclude same-family models.
    candidate_prefix = _model_family(candidate_model)

    # Prefer models from different families.
    different_family: list[str] = []
    same_family: list[str] = []
    for m in available_models:
        if m == candidate_model:
            continue
        if _model_family(m) == candidate_prefix:
            same_family.append(m)
        else:
            different_family.append(m)

    # Fill panel from different families first, then same-family.
    panel = different_family[:panel_size]
    if len(panel) < panel_size:
        remaining = panel_size - len(panel)
        panel.extend(same_family[:remaining])

    return panel


def _model_family(model_id: str) -> str:
    """Extract model family prefix for grouping.

    Splits on ``/`` first (e.g. ``"openai/gpt-4o"`` -> ``"openai"``),
    then falls back to splitting on ``-`` (e.g. ``"gpt-4o"`` -> ``"gpt"``).
    """
    if "/" in model_id:
        return model_id.split("/", 1)[0].lower()
    if "-" in model_id:
        return model_id.split("-", 1)[0].lower()
    return model_id.lower()


# ── Verdict parsing and aggregation ────────────────────────────────────


def _parse_verdict(text: str) -> str:
    """Extract a verdict from a panel member's response.

    Returns one of ``"CONFIRMED"``, ``"REFUTED"``, ``"UNCERTAIN"``.
    Falls back to ``"UNCERTAIN"`` if the verdict line is missing or
    unparseable.
    """
    match = _VERDICT_PATTERN.search(text)
    if match:
        return match.group(1).upper()
    # Fallback: scan for keywords in the entire response.
    upper = text.upper()
    if "REFUTED" in upper:
        return "REFUTED"
    if "CONFIRMED" in upper:
        return "CONFIRMED"
    return "UNCERTAIN"


def aggregate_verdicts(
    panel_results: Sequence[PanelMemberResult],
) -> tuple[str, float]:
    """Derive a final verdict from panel member results.

    Returns ``(verdict, confidence)`` where *confidence* is the
    fraction of panel members agreeing with the majority verdict.
    Uses simple majority: if no verdict achieves >50%, the result
    is ``"UNCERTAIN"``.
    """
    if not panel_results:
        return "UNCERTAIN", 0.0

    counts: dict[str, int] = {"CONFIRMED": 0, "REFUTED": 0, "UNCERTAIN": 0}
    for r in panel_results:
        key = r.verdict if r.verdict in counts else "UNCERTAIN"
        counts[key] += 1

    total = len(panel_results)
    majority_threshold = total / 2.0

    # Check CONFIRMED and REFUTED first; fall back to UNCERTAIN.
    for verdict in ("CONFIRMED", "REFUTED"):
        if counts[verdict] > majority_threshold:
            return verdict, counts[verdict] / total

    return "UNCERTAIN", counts["UNCERTAIN"] / total


# ── Main verifier ──────────────────────────────────────────────────────


class AdversarialVerifier:
    """Verify a candidate response using an independent model panel.

    Parameters
    ----------
    backend:
        Any object satisfying the ``LLMBackend`` protocol.
    available_models:
        Full list of model ids that can serve on verification panels.
    panel_size:
        Number of models to include on each panel (default ``3``).
    temperature:
        Temperature for panel member calls (default ``0.3``; lower
        values yield more deterministic critiques).
    """

    def __init__(
        self,
        backend: LLMBackend,
        available_models: Sequence[str],
        *,
        panel_size: int = 3,
        temperature: float = 0.3,
    ) -> None:
        self._backend = backend
        self._available_models = list(available_models)
        self._panel_size = panel_size
        self._temperature = temperature

    async def verify(
        self,
        candidate: str,
        *,
        task: str,
        candidate_model: str = "",
    ) -> VerificationResult:
        """Ask an independent panel to verify *candidate*.

        Parameters
        ----------
        candidate:
            The response text to verify.
        task:
            The original task or prompt that produced the candidate.
        candidate_model:
            The model id that generated the candidate.  Used to
            exclude it (and its family) from the verification panel.
        """
        panel = select_panel(
            self._available_models,
            candidate_model,
            panel_size=self._panel_size,
        )

        if not panel:
            logger.warning("No panel members available for adversarial verification")
            return VerificationResult(
                verdict="UNCERTAIN",
                confidence=0.0,
                candidate_model=candidate_model,
                panel_models=[],
            )

        prompt_content = _VERIFICATION_PROMPT.format(
            task=task,
            candidate=candidate,
        )
        messages = [ChatMessage(role="user", content=prompt_content)]

        async def _query_panel_member(model: str) -> PanelMemberResult:
            try:
                response = await self._backend.chat(
                    messages,
                    model=model,
                    temperature=self._temperature,
                )
                verdict = _parse_verdict(response.content)
                return PanelMemberResult(
                    model=model,
                    verdict=verdict,
                    raw_response=response.content,
                )
            except Exception as exc:
                logger.warning(
                    "Panel member %s failed: %s",
                    model,
                    exc,
                )
                return PanelMemberResult(
                    model=model,
                    verdict="UNCERTAIN",
                    raw_response=f"Error: {exc}",
                )

        panel_results = await asyncio.gather(*[_query_panel_member(m) for m in panel])
        results_list = list(panel_results)

        verdict, confidence = aggregate_verdicts(results_list)

        return VerificationResult(
            verdict=verdict,
            panel_results=results_list,
            confidence=confidence,
            candidate_model=candidate_model,
            panel_models=panel,
        )
